[tool.poetry]
name = "Obfuscation Detecting"
version = "0.0.0"
description = ""
authors = [
    "Maksim Skoblyuk <mskobluk@rivison.ru>"
]
readme = "README.md"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
pydantic = "^2.6.2"
fastapi-pagination = "^0.12.17"
uvicorn = "^0.27.1"
python-multipart = "^0.0.9"
minio = "^7.2.4"
celery = "^5.3.6"
flower = "^2.0.1"
redis = "^5.0.1"
catboost = "^1.2.3"
lightgbm = "^4.3.0"
pymongo = "^4.6.2"
xgboost = "1.7.3"
scikit-learn = "1.1.3"
pydantic-settings = "^2.3.2"

[tool.poetry.group.dev.dependencies]
ruff = "~0"
mypy = "^1.5"
poethepoet = "~0"
watchdog = {extras = ["watchmedo"], version = "^4.0.0"}

[tool.poe.tasks.mypy]
shell = "mypy ."

[tool.poe.tasks.ruff]
shell = "ruff check --no-cache --show-source --show-fixes --fix ."

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
